apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkVTNThMSHJNZ2h5QmdIOWRZZ0dRaDRKNE95VHpKT0prSjg4eUhVM3djMFEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudC10b2tlbi1uNWhtZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMzkxZGM2NDAtNGM4Mi00MTE3LWIyYTAtMjJiMmQyNWFlZWM1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ29jZDpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.lF7aBYZRnRCgOtaLD8084pbOdl-X54hdcFHKfKvTM0B0fC8Y8pVVrAd0h9MBUa02CoIWgBkXPilP2uqYjpn1aah1diRYOql6Jv8ttoW0-I1PwtzsNUM-ZwGjB7m4YJFY7xx76HfDBxJ8LRzqEJpIWpWGry_ifjDn5jjr0CTWqCWaui5ZYGXPlSDUue4kKaKxaWRyjKq3I3dCjnesx6bB__bdWkuniOrpD7yWTpp0IYIGKrAwnyLjZWCJqsx6bYguqW5RtIQ-8KVgDqvbycZeHcHWSOzOcMN9--3thb7ENefvpjLZ9rioRGqCqlUkRMRYb6SCcrEUSasjoZj9PipYAw'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: prometheus-grafanadatasource.yaml
