apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
  namespace: argocd
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ind5MmNuNUt2aHVKYXMxbEkwa1JhMWUyMEY4Uk9ReWZpdkhFaXpnTWtCNG8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudC10b2tlbi1uc2R0ZyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZjJhZWY5NjMtNWVkZS00ZGQ4LTljM2YtNmZjMmU0ZDk2NGNlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ29jZDpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.RjLRBkrcuXKIWOiNzVnCzqNnmhWK52WBz3STu4Ck6NXylcZC_Ic7AXYiSA3TNeZ5_yNfa-z6wF41vzEx_rEg3tQd055iQ2zhc4AAU7hATmY6585nq4SMBBuPMdsljerMqHXTqlHjj0_KtXSGhY0g-lxEemRy_9-9ICNxFrH7ui5-U4oFXf-yOpVGZVth5ITQxxJ_9UMf9XmWF4bJ3SQQ0c4umzrWfNiUwpr-ke2XjnMbGfQDNvjYNcc36pT5qT0IHu9jQa38LP77TZ_Rd_9mv5VRkK56Be2Vcgywk0aDJISuY0_vgE88VPVuaioj_8SyNEtyBTkXeUMEztvyMwWWew'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: prometheus-grafanadatasource.yaml
