apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
  namespace: argocd
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: >-
          Bearer
          eyJhbGciOiJSUzI1NiIsImtpZCI6Ind5MmNuNUt2aHVKYXMxbEkwa1JhMWUyMEY4Uk9ReWZpdkhFaXpnTWtCNG8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudC10b2tlbi1wbWJxbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmMxNmUzMGMtMjcwMS00MTRiLTliNmQtM2YzMGE2ODM4NjRjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ29jZDpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.KsnKaHifnnZx2CgHlAflDez2TtPUCd8CSyHlscqER35e-3YRzk888S_E6Rfn-m9Jgc5hRgmtRW8zqS_flbk4rFQSIg66ceBknujkbctj_FC0aTPmgwsagMhZBFlRLcfMYQgmmIDoBblyuoZbCbBw2fTrF7wkJ8vGgOIEUv9hl8xfY7UkwEenbJ4ILga7DsHJiU-6Tl-wmN70pVDZLLVKIJNoU-zcFXUrV2Qv6wUzpaS0VBvbzjGTyj-F_ytCBr5rHChO1aKxtwWUnDZhM8ddK3QW56reTknqT3iahF9l7W9W99ohitUw84OF-x5ASQNGngA66FhUcVYeL3J5w-7TWw
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: prometheus-grafanadatasource.yaml
