apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkVTNThMSHJNZ2h5QmdIOWRZZ0dRaDRKNE95VHpKT0prSjg4eUhVM3djMFEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudC10b2tlbi1xZ2xnbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTRhZDBmMWUtNzhlYi00MWE2LWIwMDMtZWRmZWI3YWRjNjg4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ29jZDpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.r6_mzvrtaCJ-qqF2dhAn11TOGxdUOfweb2g5zpjSPkvr4EKTE_7WdxCpHE0u2wXQdrWU3Uf3xk0CuqIyrJs2lfz5ofiugR_cax-RHGujdbOX_LzwxAbwzBjrkO43rVN6KjcpJZCQVXeqNU_9if9V0HtsRlfep8Q5FGafJQGjQ6AFTyoqo8o7XFIDa4MH3JZQM2moek_eRtbXnJyAocHJ4vU0L-bLqhDZD4Pu-dgNQWNOoynYHMFNpf_u6yBgXVwjd2Oeq0xB1qizDNe8H1a6RFhy3xtEVvMzlkiHcuK3YO6-wt95KLP6BAUjFsgyviY9b10RdWM9jwefzC8PREp4bA'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: prometheus-grafanadatasource.yaml
