apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkVTNThMSHJNZ2h5QmdIOWRZZ0dRaDRKNE95VHpKT0prSjg4eUhVM3djMFEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudC10b2tlbi1oOW54YyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZWRhYjZlOWMtM2I4MC00NmEyLTk2YjUtYjU1MDZjMDRhY2EyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ29jZDpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.YeZg_JEtWzxMVtx11u1F37bBwAuNWdIEwwjS5Dlxk1vCHQnQ1t-LTSnWUsqogTeOW_rv65XUN-wExBmmBnoj1wWjaeBHqhUnX9_mpyGzeeSlEMZvrdJm9LAww7yrhwW1v3_yoXgoJth7tg1YbFj13NSy_m6vi6ciXcjnwond6XcRIG46vbF1lerxfUvYoXqkp89zdKke3O25g8xNPR7iK6xPY2PhFw0e2ZkDWEdOaKUkZx-i4C1iz8FPypAf610mcL48XwsgK7C13i6WzaDETrAgK0EP-ZXfT2KR0aegSVGa_OX0rCBQdtNsQwA3pFM6Gv4s4Tnedb5sbIYKPSxcag'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: prometheus-grafanadatasource.yaml
