apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: cluster-monitoring-datasource
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ims3RFNnaC0zdnRWaEpVQVJNRzNqbXVpZ2tnSWRpZXFFQXlxb3dXalYzZDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteS1ncmFmYW5hLW9wZXJhdG9yIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdyYWZhbmEtc2VydmljZWFjY291bnQtdG9rZW4teGx0d3MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjcyMjY5ZWRhLWZlMzAtNDRlZC05YzkxLTAxM2NiYTU1Mjg4NCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpteS1ncmFmYW5hLW9wZXJhdG9yOmdyYWZhbmEtc2VydmljZWFjY291bnQifQ.EMl74vO88NtrlFEXrLUzWnuZDQFQSghHVeXcoWE1M0kantMWw5bMshE_URf0m7Bt9h9xTuJnAfzrfLLlQL95T0Xkx6r_2Aegch4kXyVEhTofKRkuoEkIe6idNtZn89NkT3UpkYacy1RUmTpTtg94BQT39w01O5BBg9CjgbU_hNK9xMXwoNI0wmcGiMmFdu-fCpENWLWqKSlGD3teX7EDCCekL4EVx4XPFufvHAzS_k0-aXNGssPZemfpo8GCxjNtJnFMaoW8Zmf_NOmBso3IPlASgQUf1p7Fs7r7SH6hdQQzjA04bHdj26Cv_CUYoN8k9cni0s-ClGN6uiFLTatUqw'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: prometheus-grafanadatasource.yaml